### ISSUE TITLE
problem with `odev code LocalDatabase Repository`

### ISSUE THREAD

**Issue by Simon-sila** [odoo-odev/odev-plugin-editor-base#1]
when i try running 
`odev code LocalDatabase Repository`
with `LocalDatabase` being a database created with `odev restore` or `odev create`, i get an error due to
https://github.com/odoo-odev/odev-plugin-editor-base/blob/main/common/editor.py#L29

when replacing DummyDatabase with LocalDatabase the problem was solved and the vscode configuration was created correctly

i would make a pull request but it doesnt look like i have the rights to do it (or i have it and i am dumb)

**Comment by brinkflew** [comment]
> i would make a pull request but it doesnt look like i have the rights to do it (or i have it and i am dumb)

I'll add you to the contributors of the project so you can create a PR ;)

**Comment by brinkflew** [comment]
Closed by #2
